### ISSUE TITLE
请问 package-lock.json 是对包版本做了什么处理吗？

### ISSUE THREAD

**Issue by harrydengchao** [youka2012/react-antd-webpack-ie8#1]
我将 `package-lock.json` 删掉之后，重新 `npm install`。然后 `npm run build` 生成的项目在 IE8 下跑不起来，提示 `addeventListener` 不兼容。  但是 直接用你这个项目里面的 `package-lock.json` 拉下来的包，就可以跑起来。  这是为啥呢？   我比对了两份文件，没发现有什么特别的地方呢

**Comment by youka2012** [comment]
你的操作系统，node，npm什么版本呢？单package.json文件默认情况下并不能确定最终安装的版本。
"pacakge-lock.json给每个依赖标明了版本, 获取地址和哈希值, 使得每次安装都会出现相同的结果. 不管你在什么机器上面或什么时候安装。”

**Comment by harrydengchao** [comment]
系统信息如下：
    System:
      OS: Windows 10
    Binaries:
      Node: 10.13.0 - D:\Program Files\nodejs\node.EXE
      npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD

---

请问，你当时生成这份`package-lock.json` 文件时，是什么开发环境呢？

**Comment by youka2012** [comment]
win7x64,node10npm6
pacakge-lock.json是很有用的，建议了解下相关资料

**Comment by harrydengchao** [comment]
感谢不吝赐教
