### ISSUE TITLE
打包后报错baseChunk.dd00a.js (1,89865)   SCRIPT438: 对象不支持“addEventListener”属性或方法

### ISSUE THREAD

**Issue by wangux** [youka2012/react-antd-webpack-ie8#3]
打包后ie8报错baseChunk.dd00a.js (1,89865)   SCRIPT438: 对象不支持“addEventListener”属性或方法

**Comment by wangux** [comment]
npm run build 打包后在ie8下运行报‘对象不支持“addEventListener”属性或方法’，百度后以为jquery版本问题，换完1.x的更低版本后仍有这个问题

**Comment by youka2012** [comment]
项目链接发一下

**Comment by wangux** [comment]
就是这个项目，拉下来后的dist能在ie8下运行，重新打包后就会报这个错

**Comment by wangux** [comment]
我换了个更低版本的可以在ie8下运行了，谢谢
